---
title: 错误处理机制 
date: 2016-06-10
tags: [Error,JavaScript]
categories: Dynamic
---

一旦代码解析或运行时出现错误，JS引擎就会自动产生并抛出一个Error实例，然后整个程序就中断在出错的位置。

`Error` -- 实例包含最基本的3个属性有`name`/ `message`/ `stack`;

存在`Error`的6个派生对象；
- `SyntaxError` -- 语法错误。`var 1a;`
- `ReferenceError` -- 引用错误，引用一个不存在的变量时候；`w`;
    + 另一个触发场景是将一个值分配给无法分配的对象。`this = 1`,`console.log() = 1`
- `RangeError` -- 范围错误，主要有几种情况，
    + 一是数组长度为负数，`new Array(-1)`;
    + Number对象的方法参数超出范围，以及函数堆栈超出最大值；
    + `(1234).toExponential(21)`
- `TypeError` -- 类型错误，当变量或参数不是预期类型时发生的错误。
    + 对字符串、数值、布尔值的原始类型的值使用new命令；`new 1`;
    + 调用对象不存在的方法时候会抛出类型错误。`a={}, a.p()`;

### 自定义错误机制

```javascript
    function useEror(message) {
        this.mes = message || "默认信息";
        this.name = "useError";
    }
    useEror.prototype = new Error();
    useEror.prototype.constructor = useEror;

    var a = new useEror("this is a");
    a.stack;    ...
```

